# name: Release Ubuntu

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   release-ubuntu:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Set up Rust
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           target: x86_64-unknown-linux-gnu
#           override: true

#       - name: Build
#         uses: actions-rs/cargo@v1
#         with:
#           command: build
#           args: --release --target x86_64-unknown-linux-gnu

#       - name: Rename binary for release
#         run: |
#           mv ./target/x86_64-unknown-linux-gnu/release/repo2md ./target/x86_64-unknown-linux-gnu/release/repo2md-x86_64-unknown-linux-gnu
